Release/0.1.0
nextimecode/web-eimilhas pull request #1
Opened 2021-04-08 12:19 UTC by marcuslamounier

2021-04-08 22:08 UTC, phdduarte requested changes

2021-04-08 22:08 UTC, phdduarte commented on src/components/atoms/formulario-label/index.tsx
> +import React from 'react'
O padrão de nome para components é 

o nome minúsculo e a segunda começando com maiúscula 

assim o nome ficaria formularoLabel

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/card/style.scss
> +}
precisa adicionar uma linha aqui

2021-04-08 22:08 UTC, phdduarte commented on src/components/atoms/separator/index.tsx
> +import './styles.scss'
coloca esses codigo do styles de cada componente no global para voce conseguir usar em outros, 
Começando a construir utility first

2021-04-08 22:08 UTC, phdduarte commented on src/components/atoms/separator/styles.scss
> +@import '../../../styles/custom/variables.scss';
colocando o syle dentro do style global 
ano vai precisar desse import de variables

2021-04-08 22:08 UTC, phdduarte commented on src/components/atoms/separator/styles.scss
> +    opacity: 1 !important;
nao é bom utilizar !important

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/card/index.tsx
> +import './style.scss'
coloca no global.

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/card/style.scss
> +@import '../../../styles/custom/variables.scss';
https://github.com/nextimecode/web-eimilhas/blob/main/src/styles/global.scss

coloca no global essas classes e utiliza ela onde precisar. 

Nao precisa do import variable 

ele é importado no global

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/depoimento/index.tsx
> +import './style.scss'
https://github.com/nextimecode/web-eimilhas/blob/main/src/styles/global.scss

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/depoimento/style.scss
> +@import '../../../styles/custom/variables.scss';
https://github.com/nextimecode/web-eimilhas/blob/main/src/styles/global.scss

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/menu/index.tsx
> +import './style.scss'
https://github.com/nextimecode/web-eimilhas/blob/main/src/styles/global.scss

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/menu/style.scss
> +@import '../../../styles/custom/variables.scss';
remover esse important

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/pessoa/index.tsx
> +import './style.scss'
remover style e colocar no global para ser utilizado em outros lugares 
muito css aqui pode ser utilizado em outros lugares.

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/pessoa/style.scss
> +@import '../../../styles/custom/variables.scss';
https://github.com/nextimecode/web-eimilhas/blob/main/src/styles/global.scss

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/promocao/index.tsx
> +import { Button } from 'react-bootstrap'
nao vamos utilizar o react bootstrap , 

pode utilizar o https://chakra-ui.com/docs/getting-started

2021-04-08 22:08 UTC, phdduarte commented on src/components/molecules/promocao/style.scss
> +@import '../../../styles/custom/variables.scss';
pode remover e colocar no geral

2021-04-08 22:08 UTC, phdduarte commented on src/components/organisms/bemvindo/index.tsx
> +import React from 'react'
o nome do component segue o padrao 

bemVindo

2021-04-08 22:08 UTC, phdduarte commented on src/components/organisms/bemvindo/index.tsx
> +import React from 'react'
também é legal colocar esses nomes em ingles.

2021-04-08 22:08 UTC, phdduarte commented on src/components/organisms/bemvindo/index.tsx
> +  {
esses valores devem ficar dentro de page e nao de organisms

2021-04-08 22:08 UTC, phdduarte commented on src/components/organisms/bemvindo/index.tsx
> +const Bemvindo = () => {
padrao do nome aqui é os dois maiúsculos 

BemVindo

2021-04-08 22:08 UTC, phdduarte commented on src/components/organisms/encontre/index.tsx
> +  const trocarRota = (event) => {
tenta usar os nomes de constantes em ingles

2021-04-08 22:08 UTC, phdduarte commented on src/components/organisms/footer-menu/style.scss
> +}
falta linha, 
Lembre se de deixar uma linha no final dos arquivos

2021-04-08 22:08 UTC, phdduarte commented on src/components/organisms/footer-owners/style.scss
> +}
linha

2021-04-08 22:08 UTC, phdduarte commented on src/components/organisms/promocoes/index.tsx
> +      foto: `${pathLugares}/rio.jpg`,
essas infromacoes devem ficar dentro de page 
e nao de organisms 

o unico componente que traz informacao é o page 
isso vai ajudar muito a velocidade de escrever e dar manutencao no codigo futuro

2021-04-08 22:08 UTC, phdduarte commented on src/components/organisms/slider/index.tsx
> +      breakpoint: { max: 3000, min: 1301 },
nao da para usar o breakpoingt do bootstrap ?? 

Se nao, 

cria esses break point no global e utiliza aqui.

2021-04-08 22:08 UTC, phdduarte commented on src/components/templates/header/index.tsx
> +        href: '#home',
novamente, essas infromacoes devem vim dentro de page e nao de template

2021-04-08 22:08 UTC, phdduarte commented on src/components/templates/section/index.tsx
> +      <div className="row m-0" style={{ paddingTop: '20vmin' }}>
nao utilize style inline

2021-04-08 22:08 UTC, phdduarte commented on src/styles/global.scss
> +@import '~bootstrap/scss/bootstrap';
falta linha

2021-04-09 18:17 UTC, marcuslamounier commented on src/components/atoms/separator/styles.scss
> +    opacity: 1 !important;
o que eu devo usar? o bootstrap sobrescreve

2021-04-09 18:17 UTC, marcuslamounier commented on src/components/molecules/menu/style.scss
> +@import '../../../styles/custom/variables.scss';
o que eu devo usar? o bootstrap sobrescreve

2021-04-09 18:25 UTC, marcuslamounier commented on src/components/organisms/slider/index.tsx
> +      breakpoint: { max: 3000, min: 1301 },
esse breakpoint é do slider, é do próprio componente

2021-04-09 19:38 UTC, phdduarte approved these changes

2021-04-09 19:38 UTC, phdduarte commented on src/components/molecules/pessoa/style.scss
> +    color: #616161;
colocar a cor assim direto ficar muito ruim a manutencao depois

2021-04-09 19:39 UTC, nextimecode approved these changes

2021-04-13 23:18 UTC, merged